# @format

name: "Github Actions Bot"
on:
    push:
        branches: ['main']
    schedule:
    - cron: "*/60 * * * *"
    workflow_dispatch:

jobs:
  cronJob:
    name: "Update data"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
            node-version: "20"
      - run: npm ci
      - run: git pull 
      - run: node index.js
      - run: |
            git config user.name  "xatta-trone"
            git config user.email "22274105+actions-user@users.noreply.github.com"
            git add -f 'data-chrome.json'
            git commit -m "🤖 Auto commit by Gihub action Bot 🤖"
            git push --force
