# @format

name: "🤖 GitHub Actions Bot 🤖"
on:
    push:
        branches: ['main']
    schedule:
    - cron: "0 0 * * *"
    workflow_dispatch:

jobs:
  cronJob:
    name: "Update data"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v4
        with:
            node-version: 20.x
      - run: npm ci
      - run: git pull 
      - run: node chrome.js
      - run: node firefox.js
      - run: |
            git config user.name  "xatta-trone"
            git config user.email "22274105+actions-user@users.noreply.github.com"
            git add -f 'data-chrome.json'
            git add -f 'data-firefox.json'
            git commit -m "🤖 Auto commit by Gihub Actions Bot 🤖"
            git push --force
